language: scala
dist: xenial
jdk: openjdk8
if: tag IS blank

branches:
  only:
  - debugtravis

before_install:
- git fetch --tags
- echo $TRAVIS_BRANCH
- echo $TRAVIS_EVENT_TYPE
- openssl aes-256-cbc -K $encrypted_b3f7bd94ef38_key -iv $encrypted_b3f7bd94ef38_iv -in private-key.pem.enc -out private-key.pem -d
- gpg --import --batch private-key.pem

stages:
- name: release
  if: branch = debugtravis

jobs:
  include:
  - stage: release
    script: sbt ci-release-sonatype

before_cache:
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local

cache:
  directories:
  - "$HOME/.sbt/1.0/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"
